### ISSUE TITLE
Console not showing up for Sublime Monokai Dark

### ISSUE THREAD

**Issue by precabal** [monikajaskolka/TeXShop-Themes#2]
Hi, there, thanks for your work. The editor looks awesome, however the console dissapears when selecting the sublime monokai dark mode.

Happens in Max OS 10.14.6, TexShop 4.44

**Comment by monikajaskolka** [comment]
Hi, I was also able to replicate the issue on my end. I will look into it.

**Comment by monikajaskolka** [comment]
Can you try using the SublimeMonokai.plist in this branch and let me know if it solves the issue for you? https://github.com/monikajaskolka/TeXShop-Themes/tree/Issue-2-ConsoleDisappear
